version: "3.9"
services:
  fnano:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./dockerfiles/python310/Dockerfile
      labels:
        - fnano
    volumes:
        - .:/mnt
    container_name: "fnano_${USER}"
    entrypoint:
      - /bin/sh
      - -c
      - |
        gunicorn app.main:app --workers 2 \
        --worker-class uvicorn.workers.UvicornWorker -b 0.0.0.0:6969
    ports:
      - "127.0.0.1:6969:6969"
    tty: true
    networks:
      - fnano

  caddy:
    image: caddy:2-alpine
    container_name: "caddy_${USER}"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "$PORT:$PORT"
      - "80:80"
      - "443:443"
    tty: true
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - "fnano_${USER}"
    networks:
      - fnano

volumes:
  caddy_data:
  caddy_config:

networks:
  fnano: {}
